package uz.com.enums;

public enum Types {

    DEFAULT("default", "default"),

    // Currency Type
    CURRENCY_TYPE(null, "CURRENCY_TYPE"),
    CURRENCY_TYPE_UZS("CURRENCY_TYPE", "CURRENCY_TYPE_UZS"),
    CURRENCY_TYPE_USD("CURRENCY_TYPE", "CURRENCY_TYPE_USD"),
    CURRENCY_TYPE_RUB("CURRENCY_TYPE", "CURRENCY_TYPE_RUB"),
    CURRENCY_TYPE_EURO("CURRENCY_TYPE", "CURRENCY_TYPE_EURO"),

    // Application Status
    APPLICATION_STATUS_TYPE(null, "APPLICATION_STATUS_TYPE"),
    APPLICATION_STATUS_EXAMINATION("APPLICATION_STATUS_TYPE", "APPLICATION_STATUS_EXAMINATION"),
    APPLICATION_STATUS_NEW("APPLICATION_STATUS_TYPE", "APPLICATION_STATUS_NEW"),
    APPLICATION_STATUS_ACCEPTED("APPLICATION_STATUS_TYPE", "APPLICATION_STATUS_ACCEPTED"),
    APPLICATION_STATUS_REJECTED("APPLICATION_STATUS_TYPE", "APPLICATION_STATUS_REJECTED"),
    APPLICATION_STATUS_CONFIRMED("APPLICATION_STATUS_TYPE", "APPLICATION_STATUS_CONFIRMED"),
    APPLICATION_STATUS_CONFIRMED_BY_SNAB("APPLICATION_STATUS_TYPE", "APPLICATION_STATUS_CONFIRMED_BY_SNAB"),

    // Supply User Position Type
    SUPPLY_USER_POSITION_TYPE(null, "SUPPLY_USER_POSITION_TYPE"),
    HEAD_OF_SUPPLY_DEPARTMENT("SUPPLY_USER_POSITION_TYPE", "HEAD_OF_SUPPLY_DEPARTMENT"),
    SUPPLY_DEPARTMENT("SUPPLY_USER_POSITION_TYPE", "SUPPLY_DEPARTMENT"),
    WAREHOUSE_AND_INVENTORY("SUPPLY_USER_POSITION_TYPE", "WAREHOUSE_AND_INVENTORY"),
    DISPATCHER("SUPPLY_USER_POSITION_TYPE", "DISPATCHER"),
    FARMER_MARKET("SUPPLY_USER_POSITION_TYPE", "FARMER_MARKET"),
    COMMERCIAL_DEPARTMENT("SUPPLY_USER_POSITION_TYPE", "COMMERCIAL_DEPARTMENT"),
    OTHER_SUPPLY_DEPARTMENT("SUPPLY_USER_POSITION_TYPE", "OTHER_SUPPLY_DEPARTMENT"),

    //Contract Properties
    CONTRACT_PROPERTY_TYPE(null, "CONTRACT_PROPERTY_TYPE"),
    PAYMENT_TERMS("CONTRACT_PROPERTY_TYPE", "PAYMENT_TERMS"),
    DELIVERY_CONDITION("CONTRACT_PROPERTY_TYPE", "DELIVERY_CONDITION"),
    PACKAGING_TYPE("CONTRACT_PROPERTY_TYPE", "PACKAGING_TYPE"),
    CERTIFICATE_AVAILABILITY("CONTRACT_PROPERTY_TYPE", "CERTIFICATE_AVAILABILITY"),
    SERVICE_MAINTENANCE("CONTRACT_PROPERTY_TYPE", "SERVICE_MAINTENANCE"),
    WARRANTY_PERIOD("CONTRACT_PROPERTY_TYPE", "WARRANTY_PERIOD"),

    // Contract Status
    CONTRACT_STATUS_TYPE(null, "CONTRACT_STATUS_TYPE"),
    CONTRACT_STATUS_NEW("CONTRACT_STATUS_TYPE", "CONTRACT_STATUS_NEW"),
    CONTRACT_STATUS_ACCEPTED("CONTRACT_STATUS_TYPE", "CONTRACT_STATUS_ACCEPTED"),
    CONTRACT_STATUS_REJECTED("CONTRACT_STATUS_TYPE", "CONTRACT_STATUS_REJECTED"),
    CONTRACT_STATUS_CONFIRMED_BY_SNAB("CONTRACT_STATUS_TYPE", "CONTRACT_STATUS_CONFIRMED_BY_SNAB"),

    //Payment Status
    PAYMENT_STATUS_TYPE(null, "PAYMENT_STATUS_TYPE"),
    PAID("PAYMENT_STATUS_TYPE", "PAID"),
    PART_PAID("PAYMENT_STATUS_TYPE", "PART_PAID"),
    NOT_PAID("PAYMENT_STATUS_TYPE", "NOT_PAID"),
    OVER_LIMIT("PAYMENT_STATUS_TYPE", "OVER_LIMIT"),

    // default
    /*ORGANIZATION_TYPE(null, "ORGANIZATION_TYPE"),*/
    UNIT_TYPE(null, "UNIT_TYPE"),
    PRODUCT_STATUS(null, "PRODUCT_STATUS"),
    COMMERCIAL_TYPE(null, "COMMERCIAL_TYPE"),
    CONTRACT_TYPE(null, "CONTRACT_TYPE"),

    // User Position
    USER_POSITION_TYPE(null, "USER_POSITION_TYPE"),
    USER_POSITION_GENERAL_DIRECTOR("USER_POSITION_TYPE", "USER_POSITION_GENERAL_DIRECTOR"),

    // Responsible User Status
    RESPONSIBLE_USER_TYPE(null, "RESPONSIBLE_USER_TYPE"),
    RESPONSIBLE_USER_TYPE_MAIN("RESPONSIBLE_USER_TYPE", "RESPONSIBLE_USER_TYPE_MAIN"),
    RESPONSIBLE_USER_TYPE_ASSISTANT("RESPONSIBLE_USER_TYPE", "RESPONSIBLE_USER_TYPE_ASSISTANT"),
    RESPONSIBLE_USER_TYPE_CONTROL("RESPONSIBLE_USER_TYPE", "RESPONSIBLE_USER_TYPE_CONTROL"),


























    USER_ACTION_TYPE(null, "USER_ACTION_TYPE"),
    USER_ACTION_ENTER("USER_ACTION_ENTER", "USER_ACTION_TYPE"),
    USER_ACTION_EXIT("USER_ACTION_EXIT", "USER_ACTION_TYPE"),

    // Resource File Type (ТЗ, Калькуляция, Смета, Проект)
    FILE_TYPE(null, "FILE_TYPE"),
    TECHNICAL_FILE("FILE_TYPE", "TECHNICAL_FILE"),
    COSTING_FILE("FILE_TYPE", "COSTING_FILE"),
    ESTIMATE_FILE("FILE_TYPE", "ESTIMATE_FILE"),
    PROJECT_FILE("FILE_TYPE", "PROJECT_FILE"),


    //Warehouse Transfer Types
    WAREHOUSE_TRANSFER_TYPE(null, "WAREHOUSE_TRANSFER_TYPE"),
    WAREHOUSE_TRANSFER_TYPE_INCOME("WAREHOUSE_TRANSFER_TYPE", "WAREHOUSE_TRANSFER_TYPE_INCOME"),
    WAREHOUSE_TRANSFER_TYPE_OUTPUT("WAREHOUSE_TRANSFER_TYPE", "WAREHOUSE_TRANSFER_TYPE_OUTPUT"),

    //Payment Calendar Types
    PAYMENT_CALENDAR_TYPE(null, "PAYMENT_CALENDAR_TYPE"),
    PAYMENT_CALENDAR_TYPE_FINANCE("PAYMENT_CALENDAR_TYPE", "PAYMENT_CALENDAR_TYPE_FINANCE"),
    PAYMENT_CALENDAR_TYPE_CONTRACT("PAYMENT_CALENDAR_TYPE", "PAYMENT_CALENDAR_TYPE_CONTRACT"),

    //Payment Calendar Types
    PAYMENT_TYPE(null, "PAYMENT_TYPE"),
    PAYMENT_TYPE_EXPENSES("PAYMENT_TYPE", "PAYMENT_TYPE_EXPENSES"),
    PAYMENT_TYPE_INCOME("PAYMENT_TYPE", "PAYMENT_TYPE_INCOME"),

    TENDER_TYPE(null, "TENDER_TYPE"),
    TENDER_TYPE_ACTING("TENDER_TYPE", "TENDER_TYPE_ACTING"),
    TENDER_TYPE_CONFIRMED("TENDER_TYPE", "TENDER_TYPE_CONFIRMED"),

    FINANCE_APPLICATION_STATUS_TYPE(null, "FINANCE_APPLICATION_STATUS_TYPE"),
    FINANCE_APPLICATION_STATUS_CONSIDERATION("FINANCE_APPLICATION_STATUS_TYPE", "FINANCE_APPLICATION_STATUS_CONSIDERATION"),
    FINANCE_APPLICATION_STATUS_ON_COMPLETION("FINANCE_APPLICATION_STATUS_TYPE", "FINANCE_APPLICATION_STATUS_ON_COMPLETION"),
    FINANCE_APPLICATION_STATUS_APPROVED("FINANCE_APPLICATION_STATUS_TYPE", "FINANCE_APPLICATION_STATUS_APPROVED"),
    FINANCE_APPLICATION_STATUS_REJECTED("FINANCE_APPLICATION_STATUS_TYPE", "FINANCE_APPLICATION_STATUS_REJECTED"),

    FINANCE_APPLICATION_TYPE(null, "FINANCE_APPLICATION_TYPE"),
    FINANCE_APPLICATION_FINANCIAL_HELP("FINANCE_APPLICATION_TYPE", "FINANCE_APPLICATION_FINANCIAL_HELP"),
    FINANCE_APPLICATION_CREDIT("FINANCE_APPLICATION_TYPE", "FINANCE_APPLICATION_CREDIT"),
    FINANCE_APPLICATION_GUARANTEE("FINANCE_APPLICATION_TYPE", "FINANCE_APPLICATION_GUARANTEE"),
    FINANCE_APPLICATION_LEASING("FINANCE_APPLICATION_TYPE", "FINANCE_APPLICATION_LEASING"),

    FIN_APPLICATION_CONFIRMATION_STATUS(null, "FIN_APPLICATION_CONFIRMATION_STATUS"),
    FIN_APPLICATION_CONFIRMATION_STATUS_ACCEPTED("FIN_APPLICATION_CONFIRMATION_STATUS", "FIN_APPLICATION_CONFIRMATION_STATUS_ACCEPTED"),
    FIN_APPLICATION_CONFIRMATION_STATUS_RETURNED("FIN_APPLICATION_CONFIRMATION_STATUS", "FIN_APPLICATION_CONFIRMATION_STATUS_RETURNED"),
    FIN_APPLICATION_CONFIRMATION_STATUS_REJECTED("FIN_APPLICATION_CONFIRMATION_STATUS", "FIN_APPLICATION_CONFIRMATION_STATUS_REJECTED"),

    FIN_APPLICATION_EXECUTION_STATUS_TYPE(null, "FIN_APPLICATION_EXECUTION_STATUS_TYPE"),
    FIN_APPLICATION_EXECUTION_STATUS_UNFULFILLED("FIN_APPLICATION_EXECUTION_STATUS_TYPE", "FIN_APPLICATION_EXECUTION_STATUS_UNFULFILLED"),
    FIN_APPLICATION_EXECUTION_STATUS_PARTIALLY("FIN_APPLICATION_EXECUTION_STATUS_TYPE", "FIN_APPLICATION_EXECUTION_STATUS_PARTIALLY"),
    FIN_APPLICATION_EXECUTION_STATUS_COMPLETED("FIN_APPLICATION_EXECUTION_STATUS_TYPE", "FIN_APPLICATION_EXECUTION_STATUS_COMPLETED");

    public String parent;
    public String value;

    Types(String parent, String value) {
        this.parent = parent;
        this.value = value;
    }

    public static Types findByValue(String key) {
        if (key == null) return DEFAULT;
        for (Types type : values()) {
            if (type.value.equals(key)) {
                return type;
            }
        }
        return DEFAULT;
    }
}
